# Book settings
title: Numerical Methods
author: Colin Denniston
logo: images/logo.png
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: false
#  use_issues_button: true
#  use_edit_page_button: true
  navbar_number_sections : false
#  announcement: "Use this JupyterBook as a <a href='https://github.com/firasm/jupyterbook_course_template' style='color:pink;'>template by clicking here</a>!"  baseurl : "https://cdenniston.github.io/NumericalMethodsModule/" # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  # google_analytics_id: UA-11111111 # add your Google Analytics Tracking Code
  comments:
    hypothesis: true
    utterances:
      repo: "CDenniston/NumericalMethodsModule"
    dokieli: true
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository: 
  url          : https://github.com/CDenniston/NumericalMethodsModule
  path_to_book : ""
  branch       : main

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - substitution

    myst_substitutions:
      INSTRUCTOR: "Colin Denniston"
      PRONOUNCE: ""
      OFFICE: "P&A ROOM 230"
      PHONE: "N/A"
      COURSE_CODE: "Phys 9610"
      SECTION: ""
      CREDITS: ""
      TITLE: "Numerical Methods"
      PREREQS: "Undergraduate Mathematics to 2nd year, working knowledge of a high level computer language"
      COREQS: ""
      TERM: "2025 Winter Term"
      ROOM: ""
      MEETING_TIMES: ""
      GRACE_PERIOD: ""
      W_DATE_1: ""
      W_DATE_2: ""
      W_DATE_3: ""
      EXAM_PERIOD: ""
      CANVAS_ID: ""
      CANVAS_LINK: ""
      ZOOM_LINK: "[Zoom](https:)"
      ANNOUNCEMENTS_LINK: "[Canvas Announcements](https://)"
      COURSE_LINK: "https://"
      FORUM_LINK: "[Ed Discussion](https://)"
      ANALYTICS_OPTOUT: "[complete this form](https://)"
      FORMAT: "Lectures, Labs, Tutorials and they will xxxx format"
      ASSOCIATE_HEAD: ""
      ANON_FEEDBACK: ""
